### ISSUE TITLE
6to5 issue on master

### ISSUE THREAD

**Issue by mcolyer** [atom/atom-shell-starter#38]
After getting a fresh checkout of master and running `script/bootstrap` and `script/build`, I get the following when I run `script/run`:

```
Running: /var/folders/2m/q3xsll2j33bbmq9zd3lctzz00000gn/T/eightoheight-build/EightOhEight.app/Contents/MacOS/EightOhEight -r .
{"_":[],"d":false,"dev":false,"h":false,"help":false,"t":false,"test":false,"v":false,"version":false,"r":".","resource-path":".","resourcePath":".","$0":"/var/folders/2m/q3xsll2j33bbmq9zd3lctzz00000gn/T/eightoheight-build/EightOhEight.app/Contents/MacOS/EightOhEight -r"}


undefined is not a function

TypeError: undefined is not a function
    at Object.loadFile [as .js] (/private/var/folders/2m/q3xsll2j33bbmq9zd3lctzz00000gn/T/eightoheight-build/EightOhEight.app/Contents/Resources/app/src/6to5.js:121:22)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.require.extensions..coffee (/private/var/folders/2m/q3xsll2j33bbmq9zd3lctzz00000gn/T/eightoheight-build/EightOhEight.app/Contents/Resources/app/src/browser/main.js:98:24)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
```

**Comment by mcolyer** [comment]
So all strings seem to be missing the `startsWith` function. Is this something that is a part of io.js but not part of regular node? Is the wrong version of node getting linked in somehow?

**Comment by paulcbetts** [comment]
@mcolyer `startsWith` is itself part of ES6, I thought I patched this away, you can just replace it with a regex

**Comment by kevinsawicki** [comment]
I think `String::startsWith` is only available in the render processes, not the browser process.
