### ISSUE TITLE
bootstrap fails on manjaro (arch linux based distro) and ubuntu

### ISSUE THREAD

**Issue by albertmatyi** [atom/atom-shell-starter#58]
I am getting the following error message: **`undefined symbol: node_module_register`***

```
atom-shell-starter$ script/bootstrap 
Node: v0.12.0
npm: v2.7.1
Installing build modules...
npm WARN engine npm@1.4.28: wanted: {"node":">=0.8","npm":"1"} (current: {"node":"0.12.0","npm":"2.7.1"})
npm WARN engine prettyjson@0.8.1: wanted: {"node":">= 0.6.0 < 0.11.0"} (current: {"node":"0.12.0","npm":"2.7.1"})
child_process: customFds option is deprecated, use stdio instead.
npm WARN engine coffee-script-redux@2.0.0-beta8: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.0","npm":"2.7.1"})
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/albertmatyi/work/tmp/atom-shell-starter/apm/node_modules/atom-package-manager/node_modules/git-utils/build/Release/git.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/albertmatyi/work/tmp/atom-shell-starter/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:8:16)
    at Object.<anonymous> (/home/albertmatyi/work/tmp/atom-shell-starter/apm/node_modules/atom-package-manager/node_modules/git-utils/lib/git.js:359:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

### I've also tried

* installing `iojs-bin` from AUR, and got other error messages, and was unable to build
* `sudo script/bootstrap` giving the same error
* using a vagrant machine (ubuntu 14.04 & `node 0.10.37`), but then the machine just **simply crashed** - several times - when I tried to use `script/bootstrap`. Without any suspicious errors in the console or syslog. 
* installing the official atom-shell release and starting the app with `atom .` but then it complained about invalid app (see output below)

```
atom-shell-starter$ atom .
[15377:0321/111323:ERROR:browser_main_loop.cc(170)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
Error opening app
The app provided is not a valid atom-shell app, please read the docs on how to write one:
https://github.com/atom/atom-shell/tree/master/docs
```

### Question
Anyone had similar issues, or could point me in the right direction on how I could use this package?

#### Additional notes:

* I've set python2.7 config option both locally and globally `npm config set python python2.7 (-g)`

**Comment by paulcbetts** [comment]
This is because you're using node 0.12.x - install 0.10.x instead

**Comment by ghuntley** [comment]
Confirmed, installing v0.10.x resolves this.
