### ISSUE TITLE
Error building on Mac

### ISSUE THREAD

**Issue by stefanbuck** [atom/atom-shell-starter#60]
I'm getting this error when running `script/build` on 10.9 and 10.10. 
What's wrong? Can anyone confirm this bug?

```
Node: v0.10.35
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Node: v0.10.35
npm: v1.4.28
Installing build modules...
Installing apm...
Installing modules ✓
Deduping modules ✓
Running "build-atom-shell" task
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 141, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 29, in main
>>     update_submodules()
>>   File "script/bootstrap.py", line 68, in update_submodules
>>     execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
>>   File "/private/var/folders/0_/9r6xw3153tsgr8sgjr64q5740000gp/T/my-app-build/atom-shell/script/lib/util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "/private/var/folders/0_/9r6xw3153tsgr8sgjr64q5740000gp/T/my-app-build/atom-shell/script/lib/util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
>> Traceback (most recent call last):
>>   File "script/bootstrap.py", line 141, in <module>
>>     sys.exit(main())
>>   File "script/bootstrap.py", line 29, in main
>>     update_submodules()
>>   File "script/bootstrap.py", line 68, in update_submodules
>>     execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
>>   File "/private/var/folders/0_/9r6xw3153tsgr8sgjr64q5740000gp/T/my-app-build/atom-shell/script/lib/util.py", line 154, in execute_stdout
>>     execute(argv)
>>   File "/private/var/folders/0_/9r6xw3153tsgr8sgjr64q5740000gp/T/my-app-build/atom-shell/script/lib/util.py", line 142, in execute
>>     raise e
>> subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
Aborted due to warnings.
```

**Comment by hongrich** [comment]
I had this problem but was able to fix it by updating Gruntfile.coffee to use the latest release of atom-shell
```
    'build-atom-shell':
      tag: "v0.22.2"
      nodeVersion: '0.22.2'
```

**Comment by leefaus** [comment]
i will try that!  thanks

**Comment by mmurdoch** [comment]
I had the same problem on Yosemite (10.10.2). Changing from `tag: "5e8c478"` to `tag: "v0.22.2"` in `build/Gruntfile.coffee` fixed it for me too.

**Comment by paulcbetts** [comment]
Fixed
