### ISSUE TITLE
Toggle full screen fails

### ISSUE THREAD

**Issue by mmurdoch** [atom/atom-shell-starter#63]
Attempting to toggle full screen mode either via the menu (View | Toggle Full Screen) or using the shortcut (Ctrl+Cmd+F) does nothing.

The following stack trace is written to the terminal:

    undefined is not a function

    TypeError: undefined is not a function
      at ApplicationMenu.<anonymous> (/[path removed]/atom-shell-starter/src/browser/application.coffee:96:40)
      at emitNone (events.js:67:13)
      at ApplicationMenu.emit (events.js:163:7)
      at /[path removed]/atom-shell-starter/src/browser/appmenu.coffee:25:22
      at MenuItem.click (/private/var/folders/lk/tlptnvwj0hv_f534ss_pl0b40000gn/T/eightoheight-build/EightOhEight.app/Contents/Resources/atom.asar/browser/api/lib/menu-item.js:44:20)
      at Function.delegate.executeCommand (/private/var/folders/lk/tlptnvwj0hv_f534ss_pl0b40000gn/T/eightoheight-build/EightOhEight.app/Contents/Resources/atom.asar/browser/api/lib/menu.js:85:71)

On Mac, Yosemite 10.10.2

**Comment by paulcbetts** [comment]
Thanks @mmurdoch!
